language: bash
services: docker

env:
  - PACKAGE=php VERSION=7.1-fpm
  - PACKAGE=php VERSION=7.2-fpm
  - PACKAGE=php VERSION=7.3-fpm
  - PACKAGE=mysql VERSION=latest
  - PACKAGE=nginx VERSION=latest

before_script:
  - env | sort
  - cd "$PACKAGE"

script:
  - |
    (
      set -Eeuo pipefail
      set -x
      docker build --pull --file "$VERSION" --tag "xtreamwayz/$PACKAGE:$VERSION" --cache-from "xtreamwayz/$PACKAGE:$VERSION" .
    )

after_script:
  - docker images

before_deploy:
  - docker login -u "$DOCKER_USER" -p "$DOCKER_PASS"

deploy:
  provider: script
  script: docker push "xtreamwayz/$PACKAGE:$VERSION"
  on:
    branch: master
