language: bash
services: docker

env:
  - PACKAGE=php VERSION=7.1-fpm
  - PACKAGE=php VERSION=7.2-fpm
  - PACKAGE=php VERSION=7.3-fpm
  - PACKAGE=mysql VERSION=latest
  - PACKAGE=nginx VERSION=latest

before_script:
  - env | sort
  - cd "$PACKAGE"

script:
  - |
    (
      set -Eeuo pipefail
      set -x
      docker build --pull --file "$VERSION.dockerfile" --tag "xtreamwayz/$PACKAGE:$VERSION" --cache-from "xtreamwayz/$PACKAGE:$VERSION" .
    )

after_script:
  - docker images

before_deploy:
  - echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin

deploy:
  - provider: script
    script: docker push "xtreamwayz/$PACKAGE:$VERSION"
    on:
      branch: master
  - provider: script
    script: docker run --rm -v "$(pwd)/$PACKAGE/readme.md:/data/README.md" -e "DOCKERHUB_USERNAME=$DOCKER_USER" -e "DOCKERHUB_PASSWORD=$DOCKER_PASS" -e "DOCKERHUB_REPO_PREFIX=xtreamwayz" -e "DOCKERHUB_REPO_NAME=$PACKAGE" sheogorath/readme-to-dockerhub;
    on:
      branch: master
