version: "3"
services:

  web:
    image: xtreamwayz/nginx
    container_name: PROJECT_ID-web
    ports:
      - "80:80"
    volumes:
      - ./public:/app/public

  php:
    image: xtreamwayz/php:7.2
    container_name: PROJECT_ID-php
    volumes:
      - .:/app

  db:
    image: xtreamwayz/mysql
    container_name: PROJECT_ID-db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=docker
      - MYSQL_PASSWORD=docker
      - MYSQL_ROOT_PASSWORD=docker
      - MYSQL_USER=docker
    #volumes:
    #  - ./data/mysql:/var/lib/mysql                          # persistent database
    #  -./resources/docker-initdb:/docker-entrypoint-initdb.d # Import .sql files

  redis:
    image: redis:3-alpine
    container_name: PROJECT_ID-redis

  mailhog:
    image: mailhog/mailhog
    container_name: PROJECT_ID-mailhog
    ports:
      - "8025:8025"
