# WordPress docker
#
# Required dir structure:
#
#	project_root
#	├── data
#	│   ├── mysql       -> Persitent MySQL data
#	│   └── wordpress   -> WordPress source code (optional if you want code completion in your IDE)
#	├── themes
#	├── plugins
#	└── uploads

version: "3"
services:

  web:
    image: xtreamwayz/nginx
    container_name: PROJECT_ID-web
    ports:
      - "80:80"
    volumes:
      - ./data/wordpress:/app/public
      - ./plugins:/app/public/wp-content/plugins
      - ./themes:/app/public/wp-content/themes
      - ./uploads:/app/public/wp-content/uploads

  php:
    image: xtreamwayz/php
    container_name: PROJECT_ID-php
    volumes:
      - ./data/wordpress:/app/public
      - ./plugins:/app/public/wp-content/plugins
      - ./themes:/app/public/wp-content/themes
      - ./uploads:/app/public/wp-content/uploads

  db:
    image: xtreamwayz/mysql
    container_name: PROJECT_ID-db
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql

  livereload:
    image: xtreamwayz/livereload
    container_name: PROJECT_ID-livereload
    ports:
      - "35729:35729"
    volumes:
      - ./data/wordpress:/app/public
      - ./plugins:/app/public/wp-content/plugins
      - ./themes:/app/public/wp-content/themes
      - ./uploads:/app/public/wp-content/uploads
