version: "3"
services:

  web:
    image: xtreamwayz/nginx
    container_name: ${PROJECT_ID}-web
    ports:
      - "80:80"
    volumes:
      - ${PROJECT_ROOT}:/app

  php:
    image: xtreamwayz/php:7.2
    container_name: ${PROJECT_ID}-php
    volumes:
      - ${PROJECT_ROOT}:/app

  db:
    image: xtreamwayz/mysql
    container_name: ${PROJECT_ID}-db
    ports:
      - "3306:3306"
    env_file: .env
    #volumes:
    #  - ${PROJECT_ROOT}/resources/mysql-dump:/docker-entrypoint-initdb.d  # Import .sql files
    #  - ${PROJECT_ROOT}/data/mysql-data:/var/lib/mysql                    # persistent database

  redis:
    image: redis:3-alpine
    container_name: ${PROJECT_ID}-redis
    ports:
      - "6379:6379"

  mailhog:
    image: mailhog/mailhog
    container_name: ${PROJECT_ID}-mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
