name: build-nginx

on:
  push:
    branches:
      - master
  schedule:
    - cron: "* 22 * * 4"

jobs:
  nginx:
    name: "nginx:latest"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build image
        run: cd nginx && docker build . --file latest.dockerfile --tag "xtreamwayz/nginx:latest" --cache-from "xtreamwayz/nginx:latest"
      - name: Push image
        run: |
          echo "${REGISTRY_PASSWORD}" | docker login --username "${REGISTRY_USERNAME}" --password-stdin
          docker push "xtreamwayz/nginx:latest"
        env:
          REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
          REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
