name: build-php-8-1

on:
  workflow_dispatch:
  push:
    paths:
      - 'php/**'
    branches: main
  schedule:
    - cron: "* 22 * * 4"

jobs:
  php_8_1_cli:
    name: "php:8.1-cli"
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: php
          file: php/8.1-cli.dockerfile
          push: true
          tags: |
            geerteltink/php:8.1-cli
            ghcr.io/geerteltink/php:8.1-cli

  php_8_1_fpm:
    name: "php:8.1-fpm"
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: php
          file: php/8.1-fpm.dockerfile
          push: true
          tags: |
            geerteltink/php:8.1-fpm
            ghcr.io/geerteltink/php:8.1-fpm
