name: build

on:
  push:
    branches:
      - master

jobs:

  php_7_4_cli:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: cd php && docker build . --file 7.4-fpm.dockerfile --tag php:7.4-fpm
