name: build-php-7-4

on:
  push:
    branches:
      - main
  schedule:
    - cron: "* 22 * * 4"

jobs:
  php_7_4_cli:
    name: "php:7.4-cli"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build image
        run: cd php && docker build . --file 7.4-cli.dockerfile --tag "xtreamwayz/php:7.4-cli" --cache-from "xtreamwayz/php:7.4-cli" --compress
      - name: Push image
        run: |
          echo "${REGISTRY_PASSWORD}" | docker login --username "${REGISTRY_USERNAME}" --password-stdin
          docker push "xtreamwayz/php:7.4-cli"
        env:
          REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
          REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}

  php_7_4_fpm:
    name: "php:7.4-fpm"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build image
        run: cd php && docker build . --file 7.4-fpm.dockerfile --tag "xtreamwayz/php:7.4-fpm" --cache-from "xtreamwayz/php:7.4-fpm" --compress
      - name: Push image
        run: |
          echo "${REGISTRY_PASSWORD}" | docker login --username "${REGISTRY_USERNAME}" --password-stdin
          docker push "xtreamwayz/php:7.4-fpm"
        env:
          REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
          REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
