name: build

on:
  push:
    branches:
      - master

jobs:
  php-7.4-cli:
    env:
      PACKAGE: php
      VERSION: 7.4-cli
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: echo "${{ PACKAGE }}:${{ VERSION }}"

  php-7.4-fpm:
    env:
      PACKAGE: php
      VERSION: 7.4-fpm
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: echo "${{ env.PACKAGE }}:${{ env.VERSION }}"

  php-7.4-test:
    env:
      PACKAGE: php
      VERSION: 7.4-test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: echo "${{ PACKAGE }}:${{ VERSION }}"
